### ISSUE TITLE
Got Loss: nan

### ISSUE THREAD

**Issue by jacky0218** [Flagro/ExcelTableCNN#4]
Hi, I try to run [excel-cnn-testing.ipynb](https://github.com/Flagro/ExcelTableCNN/blob/main/excel-cnn-testing.ipynb), but got the following reslults.
```
Epoch 0: Loss: nan
Epoch 1: Loss: nan
Epoch 2: Loss: nan
Epoch 3: Loss: nan
Epoch 4: Loss: nan
Epoch 5: Loss: nan
Epoch 6: Loss: nan
Epoch 7: Loss: nan
Epoch 8: Loss: nan
Epoch 9: Loss: nan
```
I think the `excel_table_cnn/dl_classification/model/fcn_backbone.py` got some problems. Any ideas for solving?
Thank you!

**Comment by acse-hy23** [comment]
I have the same problem, may I ask how did you fix this?
